### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by 3togo** [antocad/FocusOnDepth#20]
When I run python train.py,. I got the following errors.

Any advice on how to fix it?

Traceback (most recent call last):
  File "C:\Users\hello\Desktop\git\FocusOnDepth\train.py", line 31, in <module>
    trainer = Trainer(config)
  File "C:\Users\hello\Desktop\git\FocusOnDepth\FOD\Trainer.py", line 24, in __init__
    self.model = FocusOnDepth(
  File "C:\Users\hello\Desktop\git\FocusOnDepth\FOD\FocusOnDepth.py", line 55, in __init__
    self.transformer_encoders = timm.create_model(model_timm, pretrained=True)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\vision_transformer.py", line 887, in vit_base_patch16_384
    model = _create_vision_transformer('vit_base_patch16_384', pretrained=pretrained, **model_kwargs)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\vision_transformer.py", line 786, in _create_vision_transformer
    model = build_model_with_cfg(
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\helpers.py", line 549, in build_model_with_cfg
    load_custom_pretrained(model, pretrained_cfg=pretrained_cfg)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\helpers.py", line 192, in load_custom_pretrained
    model.load_pretrained(pretrained_loc)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\vision_transformer.py", line 488, in load_pretrained
    _load_weights(self, checkpoint_path, prefix)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\vision_transformer.py", line 624, in _load_weights
    w = np.load(checkpoint_path)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 422, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 178, in __init__
    _zip = zipfile_factory(fid)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 101, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\hello\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by 3togo** [comment]
using Linux instead of Windows could avoid this problem
